server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stayfinder
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: "lAETEeWQtwQtb94brSKY7YSi9j7ZJTRNgNoXQJithG4X2XI4xuiPDvZ+7DWqS2Ng"
    access-token-expiration: 28800 # 8 hours
    refresh-token-expiration: 604800 # 7 days
